name: notify
on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Send notification on Slack when master branch has been updated
        uses: pullreminders/slack-action@v1
        with:
          args: '{\"channel\": \"CNTTJKLR5\", \"test\": \"There are some changes in dotfiles\"}'
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
